name: flutter_dart_momorepo

repository: https://github.com/kosukesaigusa/full_dart_monorepo

packages:
  - client/**
  - common/**
  - server/**

scripts:
  generate:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.
