name: dart_firebase_functions
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.5

dependencies:
  dart_firebase_admin: 
    git:
      url: https://github.com/kosukesaigusa/dart_firebase_admin.git
      path: packages/dart_firebase_admin
      ref: 9b6856f5e4a80d094534a5b078114087fcaa0522
  functions_framework: ^0.4.3+1
  protobuf: ^3.1.0

dev_dependencies:
  test: ^1.24.0
