name: full_dart_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  # Required for dart_firebase_admin >=0.2.0
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # dart_firebase_admin: ^0.3.0
  dart_firebase_admin: 
    path: ../dart_firebase_admin/packages/dart_firebase_admin
  # firestore_document_models: 
  #   path: ../../common/firestore_document_models
  functions_framework: ^0.4.0
  http: ^1.0.0
  protobuf_helpers_for_functions:
    path: ../protobuf_helpers_for_functions
  shelf: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  functions_framework_builder: ^0.4.0
  test: ^1.15.7
  test_process: ^2.0.0
