name: 🚚 Deploy to Cloud Run

on:
  workflow_dispatch:

env:
  REGION: asia-northeast1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [oncreatetodo, onupdatetodo, ondeletetodo, onwritetodo]

    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: Set up Dart
        uses: 'dart-lang/setup-dart@v1'
        with:
          sdk: stable

      - name: Generate Dockerfile
        run: |
          rm -f Dockerfile
          sed "s/TARGET_PLACEHOLDER/${{ matrix.service }}/" Dockerfile.template > Dockerfile

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: '${{ secrets.PROJECT_ID }}'
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: Build
        run: |
          dart pub get
          dart pub run build_runner build --delete-conflicting-outputs
        working-directory: server/full_dart_server

      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          source: ./
          service: ${{ matrix.SERVICE }}
          region: ${{ env.REGION }}
          env_vars: ENVIRONMENT=production
          secrets: |
            PROJECT_ID=PROJECT_ID:latest
            CLIENT_ID=CLIENT_ID:latest
            CLIENT_EMAIL=CLIENT_EMAIL:latest
            PRIVATE_KEY=PRIVATE_KEY:latest
