name: 🚚 Deploy to Cloud Run

on:
  workflow_dispatch:

env:
  REGION: asia-northeast1

jobs:
  set_matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          json=$(cat ${{ github.workspace }}/.github/actions/services.yml| ruby -ryaml -rjson -e 'puts YAML.load(STDIN).to_json')
          echo "matrix=${json}" >> $GITHUB_OUTPUT

  call_reusable_deploy_workflow:
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: set_matrix
    uses: ./.github/workflows/reusable_deploy_workflow.yml
    with:
      matrix: ${{ needs.set_matrix.outputs.matrix }}
