name: 🚚 Deploy to Cloud Run

on:
  workflow_dispatch:

jobs:
  set_matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: sudo snap install yq

      - name: Set matrix
        id: set-matrix
        run: |
          json=$(yq eval -o=json .github/actions/services.yml)
          echo $json
          echo "matrix=${json}" >> $GITHUB_OUTPUT

  call_reusable_deploy_workflow:
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: set_matrix
    uses: ./.github/workflows/reusable_deploy_workflow.yml
    with:
      matrix: ${{ needs.set_matrix.outputs.matrix }}
    secrets: inherit
